version: '3.8'
services:
  postgres:
    image: postgres:14.8-alpine
    container_name: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    depends_on: 
      - 'postgres'
    environment:
      PGADMIN_DEFAULT_EMAIL: pg.admin@email.com
      PGADMIN_DEFAULT_PASSWORD: password
    volumes:
      - pgadmin-data:/var/lib/pgadmin
    ports:
      - "8000:80"

volumes:
  postgres-data:
  pgadmin-data: